services:
  # --- BANCO DE DADOS (PostgreSQL) ---
  postgres:
    image: postgres:15-alpine
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- MESSAGE BROKER (RabbitMQ) ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # --- MICROSERVIÇO 1 (Auth - Produtor) ---
  auth-service:
    build: ./apps/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASS=admin
      - JWT_SECRET=uma_chave_super_secreta_e_longa_para_o_jwt_funcionar_123456
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # --- MICROSERVIÇO 2 (Mail - Consumidor) ---
  mail-service:
    build: ./apps/mail-service
    container_name: mail-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - MAILTRAP_HOST=sandbox.smtp.mailtrap.io
      - MAILTRAP_PORT=2525
      - MAILTRAP_USER=bb758a3a7bdd19
      - MAILTRAP_PASS=e6a7400cf94844

volumes:
  postgres_data: