services:
  # --- BANCO DE DADOS (PostgreSQL) ---
  postgres:
    image: postgres:15-alpine
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pet-network

  # --- MESSAGE BROKER (RabbitMQ) ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_prometheus && rabbitmq-server"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pet-network

  # --- MICROSERVIÇO 1 (Auth - Produtor) ---
  auth-service:
    build: ./apps/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASS=admin
      - JWT_SECRET=uma_chave_super_secreta_e_longa_para_o_jwt_funcionar_123456
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - pet-network

  # --- MICROSERVIÇO 2 (Mail - Consumidor) ---
  mail-service:
    build: ./apps/mail-service
    container_name: mail-service
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - MAILTRAP_HOST=sandbox.smtp.mailtrap.io
      - MAILTRAP_PORT=2525
      - MAILTRAP_USER=bb758a3a7bdd19
      - MAILTRAP_PASS=e6a7400cf94844
    networks:
      - pet-network

    # --- API GATEWAY ---
  api-gateway:
    build: ./apps/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080" # Porta oficial de acesso
    depends_on:
      - auth-service
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - pet-network

  # --- MONITORAMENTO (Prometheus + Grafana) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pet-network

  #--- GRAFANA ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=GrafanaAdmin12391
    networks:
      - pet-network
    depends_on:
      - prometheus

  # --- LOGS (Loki + Promtail + Redis) ---
  redis:
    image: redis:alpine
    container_name: petshop-redis
    ports:
      - "6379:6379"
    networks:
      - pet-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - pet-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/promtail/config.yml:/etc/promtail/config.yml
    networks:
      - pet-network

# --- DEFINIÇÃO DE REDES E VOLUMES ---
networks:
  pet-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: