global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'mail-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mail-service:8082']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]